/* compton1-test.mac */

  /* UNPOLARIZED CASE */

  invar(D(p1,p1) = m^2,D(p2,p2) = m^2,D(k1,k1) = 0,D(k2,k2) = 0,
             D(p1,p2) = -D(k2,p1)+D(k1,p1)+m^2,D(k1,p2) = D(k2,p1),
             D(k2,p2) = D(k1,p1),D(k1,k2) = D(k1,p1)-D(k2,p1));
  done;
  
  m1sq:tr(m+p2,mu,m-k2+p1,nu,m+p1,nu,m-k2+p1,mu);
  32*m^4-32*D(k2,p1)*m^2+32*D(k1,p1)*D(k2,p1);
  
  m2sq:tr(m+p2,mu,m+k1+p1,nu,m+p1,nu,m+k1+p1,mu);
  32*m^4+32*D(k1,p1)*m^2+32*D(k1,p1)*D(k2,p1);
  
  m1m2sq:tr(m+p2,mu,m-k2+p1,nu,m+p1,mu,m+k1+p1,nu);
  32*m^4-16*D(k2,p1)*m^2+16*D(k1,p1)*m^2;
  
  m2m1sq:tr(m+p2,mu,m+k1+p1,nu,m+p1,mu,m-k2+p1,nu);
  32*m^4-16*D(k2,p1)*m^2+16*D(k1,p1)*m^2;
  
  m1m2sq-m2m1sq;
  0;
  
  Mssq_unpol:expand((-2*m1m2sq)/(4*D(k2,p1)*D(k1,p1))
                          +m2sq/(4*D(k1,p1)^2)+m1sq/(4*D(k2,p1)^2));
  -16*m^4/(D(k1,p1)*D(k2,p1))+8*m^4/D(k2,p1)^2+8*m^4/D(k1,p1)^2
                                  -16*m^2/D(k2,p1)+16*m^2/D(k1,p1)
                                  +8*D(k2,p1)/D(k1,p1)+8*D(k1,p1)/D(k2,p1);
                                  
   Mssq_unpol8:expand(Mssq_unpol/8);
   -2*m^4/(D(k1,p1)*D(k2,p1))+m^4/D(k2,p1)^2+m^4/D(k1,p1)^2-2*m^2/D(k2,p1)
                                 +2*m^2/D(k1,p1)+D(k2,p1)/D(k1,p1)
                                 +D(k1,p1)/D(k2,p1);
                                 
  (assume(m > 0,k > 0,kp > 0,th >= 0,th <= %pi),
        comp_def(p1(m,0,0,0),k1(k,0,0,k),k2(kp,kp*sin(th),0,kp*cos(th)),
                p2(-kp+k+m,-kp*sin(th),0,k-kp*cos(th))),
        kp_rule:solve(VP(-k2+k1+p1,-k2+k1+p1) = ev_invar(D(p2,p2)),kp),
        rhs (part (kp_rule,1)));
   -k*m/(k*cos(th)-m-k);
   
   M1t5:take_parts(Mssq_unpol8,1,5);
   -2*m^4/(D(k1,p1)*D(k2,p1))+m^4/D(k2,p1)^2+m^4/D(k1,p1)^2-2*m^2/D(k2,p1)
                                 +2*m^2/D(k1,p1);
                                 
   M6t7:take_parts(Mssq_unpol8,6,7);
   D(k2,p1)/D(k1,p1)+D(k1,p1)/D(k2,p1);
   
   M6t7:D_sub(M6t7,[D(k1,p1),D(k2,p1)]);
   kp/k+k/kp;
   
   M1t5:D_sub(M1t5,[D(k1,p1),D(k2,p1)]);
   -2*m^2/(k*kp)+m^2/kp^2+m^2/k^2-2*m/kp+2*m/k;
   
   M1t5:trigsimp(ev(M1t5,kp_rule));
   cos(th)^2-1;
   
   M1t5:ts(M1t5,th);
   -sin(th)^2;
   
   Mssq_unpol:8*(M6t7+M1t5);
   8*(-sin(th)^2+kp/k+k/kp);
   
   /* UNPOLARIZED ELECTRONS, POLARIZED PHOTONS */
   
   
   (
        invar(D(e1,e1) = -1,D(k1,e1) = 0,D(e2,e2) = -1,D(k2,e2) = 0,
             D(p1,e1) = 0,D(p1,e2) = 0,D(e1,p2) = -D(e1,k2),
             D(e2,p2) = D(e2,k1)),
         M1sq:tr(m+p2,e1,m-k2+p1,e2,m+p1,e2,m-k2+p1,e1));
     8*D(k1,p1)*D(k2,p1)-16*D(e1,k2)^2*D(k2,p1);
     
   M2sq:tr(m+p2,e2,m+k1+p1,e1,m+p1,e1,m+k1+p1,e2);
   8*D(k1,p1)*D(k2,p1)+16*D(e2,k1)^2*D(k1,p1);
   
   M1m2sq:tr(m+p2,e1,m-k2+p1,e2,m+p1,e1,m+k1+p1,e2);
   -16*D(e1,e2)^2*D(k1,p1)*D(k2,p1)+8*D(k1,p1)*D(k2,p1)
                                       +8*D(e2,k1)^2*D(k2,p1)
                                       -8*D(e1,k2)^2*D(k1,p1);
                                       
   M2m1sq:tr(m+p2,e2,m+k1+p1,e1,m+p1,e2,m-k2+p1,e1);
   -16*D(e1,e2)^2*D(k1,p1)*D(k2,p1)+8*D(k1,p1)*D(k2,p1)
                                       +8*D(e2,k1)^2*D(k2,p1)
                                       -8*D(e1,k2)^2*D(k1,p1);
                                       
   M2m1sq-M1m2sq;
   0;
   
   Mssq_pol:expand((-2*M1m2sq)/(4*D(k2,p1)*D(k1,p1))
                        +M2sq/(4*D(k1,p1)^2)+M1sq/(4*D(k2,p1)^2));
   2*D(k2,p1)/D(k1,p1)+2*D(k1,p1)/D(k2,p1)+8*D(e1,e2)^2-4;
   
   Mssq_pol:D_sub(Mssq_pol,[D(k1,p1),D(k2,p1)]);
   2*kp/k+2*k/kp+8*D(e1,e2)^2-4;
   
   