/* compton0-test.mac */

( invar (D(p1,p1) = m^2,
         D(p1,k1) = (s-m^2)/2,
         D(p1,k2) = -(u-m^2)/2,
         D(p1,p2) = (s+u)/2,
         D(p2,p2) = m^2,
         D(p2,k1) = -(u-m^2)/2,
         D(p2,k2) = (s-m^2)/2,
         D(k1,k1) = 0,
         D(k1,k2) = (s+u)/2 - m^2,
         D(k2,k2) = 0),
         
    t_munu:Gm(mu,nu)-UI(p1,nu)*UI(p2,mu)/D(k1,p1)
                       +UI(p1,mu)*UI(p2,nu)/D(k1,p2),
                       
    Mssq : ratsimp ( 4*(Con (t_munu^2) -2) ),
    
    expand (Mssq) );
    
   8*s^2*u^2/(s^2*u^2-2*m^2*s*u^2+m^4*u^2-2*m^2*s^2*u+4*m^4*s*u-2*m^6*u
                        +m^4*s^2-2*m^6*s+m^8)
       +8*m^4*u^2/(s^2*u^2-2*m^2*s*u^2+m^4*u^2-2*m^2*s^2*u+4*m^4*s*u-2*m^6*u
                          +m^4*s^2-2*m^6*s+m^8)
       -32*m^6*u/(s^2*u^2-2*m^2*s*u^2+m^4*u^2-2*m^2*s^2*u+4*m^4*s*u-2*m^6*u
                         +m^4*s^2-2*m^6*s+m^8)
       +8*m^4*s^2/(s^2*u^2-2*m^2*s*u^2+m^4*u^2-2*m^2*s^2*u+4*m^4*s*u-2*m^6*u
                          +m^4*s^2-2*m^6*s+m^8)
       -32*m^6*s/(s^2*u^2-2*m^2*s*u^2+m^4*u^2-2*m^2*s^2*u+4*m^4*s*u-2*m^6*u
                         +m^4*s^2-2*m^6*s+m^8)
       +40*m^8/(s^2*u^2-2*m^2*s*u^2+m^4*u^2-2*m^2*s^2*u+4*m^4*s*u-2*m^6*u
                       +m^4*s^2-2*m^6*s+m^8);
                       
   /* lab frame evaluation */
 
  (assume (m > 0, k > 0, kp > 0, th >= 0, th <= %pi ),
       comp_def ( p1( m,0,0,0),
           k1( k,0,0,k),
           k2 (kp,kp*sin(th),0,kp*cos(th)),
           p2 (m+k-kp,-kp*sin(th),0,k-kp*cos(th)) ),
       kp_rule : solve (
          VP (p1+k1-k2,p1+k1-k2) = ev_invar (D(p2,p2)),   kp ),
       rhs (first (kp_rule)));
  -k*m/(k*cos(th)-m-k);         
       
  s_th : VP (p1+k1,p1+k1);
  m^2+2*k*m;
 
  (t_th : ( VP (k1-k2,k1-k2),ev(%%,kp_rule)),
        expand (t_th));
  2*k^2*m/(k*cos(th)-m-k)-2*k^2*m*cos(th)/(k*cos(th)-m-k);
  
   u_th : ( VP (k2-p1,k2-p1),ev(%%,kp_rule));
   2*k*m^2/(k*cos(th)-m-k)+m^2;  
   
   (Mssq_lab : factor (sub_stu (Mssq)),
         expand (Mssq_lab));
   4*cos(th)^2+4;
   
   (invar (D(e1,e1) = -1,
        D(k1,e1) = 0,
        D(e2,e2) = -1,
        D(k2,e2) = 0,
        D(p1,e1) = 0,
        D(p1,e2) = 0,
        D(e1,p2) = -D(e1,k2),
        D(e2,p2) = D(e2,k1)),
       Ampl : -2*D(e1,e2) + D(e2,a)*D(e1,b)/(s-m^2) + D(e2,c)*D(e1,d)/(u-m^2));
  D(c,e2)*D(d,e1)/(u-m^2)+D(a,e2)*D(b,e1)/(s-m^2)-2*D(e1,e2);

 Ampsq:expand(Ampl^2);
 D(c,e2)^2*D(d,e1)^2/(u^2-2*m^2*u+m^4)
       +2*D(a,e2)*D(b,e1)*D(c,e2)*D(d,e1)/(s*u-m^2*u-m^2*s+m^4)
       -4*D(c,e2)*D(d,e1)*D(e1,e2)/(u-m^2)
       +D(a,e2)^2*D(b,e1)^2/(s^2-2*m^2*s+m^4)
       -4*D(a,e2)*D(b,e1)*D(e1,e2)/(s-m^2)+4*D(e1,e2)^2;
       
 Ampsq1:subst([a = k2+2*p2,b = k1+2*p1,c = 2*p1-k2,d = 2*p2-k1],Ampsq);
 D(e1,2*p2-k1)^2*D(e2,2*p1-k2)^2/(u^2-2*m^2*u+m^4)
       +2*D(e1,2*p1+k1)*D(e1,2*p2-k1)*D(e2,2*p1-k2)*D(e2,2*p2+k2)
        /(s*u-m^2*u-m^2*s+m^4)-4*D(e1,e2)*D(e1,2*p2-k1)*D(e2,2*p1-k2)/(u-m^2)
       +D(e1,2*p1+k1)^2*D(e2,2*p2+k2)^2/(s^2-2*m^2*s+m^4)
       -4*D(e1,e2)*D(e1,2*p1+k1)*D(e2,2*p2+k2)/(s-m^2)+4*D(e1,e2)^2;
       
 Ampsq2:ev_Ds(Ampsq1);
 4*D(e1,e2)^2;
 
 
 
 
